Repository spkenv/spk, pull requests merged in 2024-10, with the labels that each got.

#1139 Update to Rust 1.82.0 and fix lints
  .github/workflows/rust.yml
  .site/spi/.spdev.yaml
  crates/spfs/src/config_test.rs
  crates/spfs/src/monitor.rs
  crates/spk-schema/crates/ident/src/request.rs
  crates/spk-storage/src/storage/runtime.rs
  rpmbuild.Dockerfile
  website/layouts/partials/logo.html
  website/layouts/partials/menu.html
  website/layouts/partials/search.html
Labels: maintenance

#1133 Fix empty Request requester in test requirements
  crates/spk-schema/src/v0/spec.rs
  crates/spk-schema/src/v0/test_spec.rs
Labels: bug, pr-chain

#1127 Add `spk info --variants-with-tests`
  crates/spk-cli/group4/src/cmd_view.rs
  crates/spk-schema/src/test.rs
Labels: enhancement, SPI AOI

#1140 Replace manual mutex with serial_test
  crates/spfs/src/config_test.rs
Labels: maintenance

#1125 Make sync progress bars optional
  Cargo.lock
  Cargo.toml
  crates/spfs-cli/common/src/args.rs
  crates/spfs-cli/common/src/lib.rs
  crates/spfs/Cargo.toml
  crates/spfs/src/check.rs
  crates/spfs/src/io.rs
  crates/spfs/src/storage/fallback/repository.rs
  crates/spfs/src/sync.rs
  crates/spfs/src/sync/reporter.rs
  crates/spk-cli/cmd-convert/Cargo.toml
  crates/spk-cli/cmd-convert/src/cmd_convert.rs
  crates/spk-cli/cmd-debug/src/cmd_debug.rs
  crates/spk-cli/cmd-env/Cargo.toml
  crates/spk-cli/cmd-env/src/cmd_env.rs
  crates/spk-cli/common/src/publish.rs
  crates/spk-cli/group3/src/cmd_import.rs
  crates/spk-cli/group3/src/cmd_import_test.rs
  crates/spk-exec/src/exec.rs
  crates/spk-exec/src/lib.rs
  crates/spk-launcher/src/main.rs
  crates/spk-schema/Cargo.toml
  crates/spk-schema/crates/foundation/Cargo.toml
  crates/spk-solve/crates/validation/Cargo.toml
  crates/spk-storage/Cargo.toml
  crates/spk-storage/src/storage/archive.rs
Labels: enhancement, SPI AOI

#1138 Bugfix: `get_unresolved_requests()` and incompatible requests
  crates/spk-cli/group1/src/cmd_bake.rs
  crates/spk-cli/group1/src/cmd_bake_test.rs
  crates/spk-solve/crates/graph/src/graph.rs
  crates/spk-solve/src/io.rs
  crates/spk-solve/src/solver.rs
  cspell.json
Labels: bug, SPI AOI, SPI-0.43

#744 Rework how packages describe how they contain the components of an embedded package
  .clippy.toml
  Cargo.lock
  crates/spk-schema/Cargo.toml
  crates/spk-schema/crates/foundation/src/ident_ops/parsing/mod.rs
  crates/spk-schema/crates/foundation/src/ident_ops/parsing/request.rs
  crates/spk-schema/crates/foundation/src/version/compat/problems.rs
  crates/spk-schema/crates/ident/src/ident_optversion.rs
  crates/spk-schema/crates/ident/src/ident_version.rs
  crates/spk-schema/crates/ident/src/lib.rs
  crates/spk-schema/crates/ident/src/parsing/ident.rs
  crates/spk-schema/crates/ident/src/parsing/mod.rs
  crates/spk-schema/src/component_embedded_packages.rs
  crates/spk-schema/src/component_spec.rs
  crates/spk-schema/src/embedded_packages_list.rs
  crates/spk-schema/src/install_spec.rs
  crates/spk-schema/src/install_spec_test.rs
  crates/spk-schema/src/lib.rs
  crates/spk-schema/src/v0/spec.rs
  crates/spk-solve/crates/graph/src/graph.rs
  crates/spk-solve/crates/solution/src/solution.rs
  crates/spk-solve/crates/validation/src/validators/components.rs
  crates/spk-solve/crates/validation/src/validators/embedded_package.rs
  crates/spk-solve/crates/validation/src/validators/pkg_request.rs
  crates/spk-solve/crates/validation/src/validators/pkg_requirements.rs
  crates/spk-solve/src/solver.rs
  crates/spk-solve/src/solver_test.rs
  cspell.json
  docs/ref/spec.md
Labels: agenda item

#1136 Add list of layers file to spfs run command
  Cargo.lock
  crates/spfs-cli/main/src/cmd_ls.rs
  crates/spfs-cli/main/src/cmd_run.rs
  crates/spfs-encoding/Cargo.toml
  crates/spfs-encoding/src/hash.rs
  crates/spfs/src/check.rs
  crates/spfs/src/error.rs
  crates/spfs/src/resolve.rs
  crates/spfs/src/runtime/live_layer.rs
  crates/spfs/src/runtime/live_layer_test.rs
  crates/spfs/src/runtime/mod.rs
  crates/spfs/src/runtime/spec_api_version.rs
  crates/spfs/src/runtime/storage.rs
  crates/spfs/src/runtime/storage_test.rs
  crates/spfs/src/sync.rs
  crates/spfs/src/tracking/env.rs
  crates/spfs/src/tracking/env_test.rs
  crates/spfs/src/tracking/mod.rs
  crates/spfs/src/tracking/tag.rs
  crates/spk-cli/cmd-env/src/cmd_env.rs
  crates/spk-cli/cmd-explain/src/cmd_explain.rs
  crates/spk-cli/common/src/flags.rs
  cspell.json
  docs/spfs/usage.md
Labels: SPI AOI, SPI-0.43
