Repository spkenv/spk, pull requests merged in 2024-09, with the labels that each got.

#1103 Remove trim_start_matches targeting '.'
  crates/spfs-vfs/src/winfsp/mount.rs
  crates/spfs/src/tracking/diff.rs
  crates/spfs/src/tracking/manifest.rs
  crates/spk-cli/cmd-build/src/cmd_build_test/mod.rs
Labels: bug

#1124 Adds support for parsing a comma-separated list of range idents
  crates/spk-schema/crates/foundation/src/ident_ops/parsing/mod.rs
  crates/spk-schema/crates/foundation/src/version/version_test.rs
  crates/spk-schema/crates/ident/src/lib.rs
  crates/spk-schema/crates/ident/src/parsing/mod.rs
  crates/spk-schema/crates/ident/src/parsing/parsing_test.rs
  crates/spk-schema/crates/ident/src/parsing/request.rs
  crates/spk-schema/crates/ident/src/range_ident.rs
  crates/spk-schema/crates/ident/src/range_ident_test.rs
Labels: SPI AOI, SPI-0.43

#1129 Preserve install environment
  Cargo.lock
  Cargo.toml
  crates/is_default_derive_macro/Cargo.toml
  crates/is_default_derive_macro/src/lib.rs
  crates/spk-cli/cmd-build/src/cmd_build_test/mod.rs
  crates/spk-schema/Cargo.toml
  crates/spk-schema/crates/foundation/src/is_default.rs
  crates/spk-schema/crates/foundation/src/lib.rs
  crates/spk-schema/crates/foundation/src/version/compat.rs
  crates/spk-schema/crates/ident/src/request.rs
  crates/spk-schema/src/build_spec.rs
  crates/spk-schema/src/build_spec_test.rs
  crates/spk-schema/src/component_spec_list.rs
  crates/spk-schema/src/embedded_packages_list.rs
  crates/spk-schema/src/environ.rs
  crates/spk-schema/src/install_spec.rs
  crates/spk-schema/src/lib.rs
  crates/spk-schema/src/metadata/meta.rs
  crates/spk-schema/src/option.rs
  crates/spk-schema/src/package.rs
  crates/spk-schema/src/recipe.rs
  crates/spk-schema/src/requirements_list.rs
  crates/spk-schema/src/spec.rs
  crates/spk-schema/src/v0/platform.rs
  crates/spk-schema/src/v0/spec.rs
  crates/spk-schema/src/validation.rs
Labels: bug

#1126 Create concrete types for Compatibility::Incompatible
  Cargo.lock
  Cargo.toml
  crates/spk-cli/common/src/error.rs
  crates/spk-schema/crates/foundation/Cargo.toml
  crates/spk-schema/crates/foundation/src/format/mod.rs
  crates/spk-schema/crates/foundation/src/version/compat.rs
  crates/spk-schema/crates/foundation/src/version/compat/compat_test.rs
  crates/spk-schema/crates/foundation/src/version/compat/mod.rs
  crates/spk-schema/crates/foundation/src/version/compat/problems.rs
  crates/spk-schema/crates/foundation/src/version/mod.rs
  crates/spk-schema/crates/foundation/src/version_range/mod.rs
  crates/spk-schema/crates/ident/Cargo.toml
  crates/spk-schema/crates/ident/src/range_ident.rs
  crates/spk-schema/crates/ident/src/request.rs
  crates/spk-schema/crates/ident/src/request_test.rs
  crates/spk-schema/src/environ.rs
  crates/spk-schema/src/option.rs
  crates/spk-schema/src/requirements_list.rs
  crates/spk-schema/src/v0/spec.rs
  crates/spk-solve/crates/graph/src/error.rs
  crates/spk-solve/crates/graph/src/graph.rs
  crates/spk-solve/crates/validation/Cargo.toml
  crates/spk-solve/crates/validation/src/error.rs
  crates/spk-solve/crates/validation/src/impossible_checks.rs
  crates/spk-solve/crates/validation/src/validators/binary_only.rs
  crates/spk-solve/crates/validation/src/validators/components.rs
  crates/spk-solve/crates/validation/src/validators/deprecation.rs
  crates/spk-solve/crates/validation/src/validators/embedded_package.rs
  crates/spk-solve/crates/validation/src/validators/options.rs
  crates/spk-solve/crates/validation/src/validators/pkg_request.rs
  crates/spk-solve/crates/validation/src/validators/pkg_requirements.rs
  crates/spk-solve/crates/validation/src/validators/var_requirements.rs
  crates/spk-solve/src/error.rs
  crates/spk-solve/src/solver.rs
  crates/spk/src/cli.rs
  docs/admin/config.md
Labels: enhancement

#1123 Add `--allow-already-editable` flag to `spfs edit`
  crates/spfs-cli/main/src/cmd_edit.rs
Labels: SPI AOI, SPI-0.43

#1131 Fix IncompatibleReason Display issues
  Cargo.lock
  Cargo.toml
  crates/spk-schema/crates/foundation/src/version/compat/mod.rs
  crates/spk-schema/crates/foundation/src/version/compat/problems.rs
Labels: bug
