Repository spkenv/spk, pull requests merged in 2024-08, with the labels that each got.

#1086 Changes needed for using Rust 1.80
  .github/workflows/rust.yml
  .site/spi/.spdev.yaml
  Cargo.lock
  Cargo.toml
  crates/sentry-miette/Cargo.toml
  crates/spfs/src/bootstrap.rs
  crates/spfs/src/graph/annotation.rs
  crates/spfs/src/graph/blob.rs
  crates/spfs/src/graph/entry.rs
  crates/spfs/src/graph/layer.rs
  crates/spfs/src/graph/manifest.rs
  crates/spfs/src/graph/platform.rs
  crates/spfs/src/graph/tree.rs
  crates/spfs/src/tracking/manifest.rs
  crates/spfs/src/tracking/tag.rs
  crates/spk-cli/cmd-env/src/cmd_env.rs
  crates/spk-schema/src/spec.rs
  crates/spk-storage/src/storage/spfs.rs
  cspell.json
  rpmbuild.Dockerfile
Labels: maintenance

#1088 Fix default origin repo not respecting --when
  crates/spk-cli/common/src/flags.rs
Labels: bug

#1060 Add solver config to control default the solver and displayed output
  crates/spk-cli/common/src/flags.rs
  crates/spk-config/src/config.rs
  crates/spk-solve/src/io.rs
Labels: enhancement, SPI AOI, SPI-0.41

#1093 Make 'Failed to resolve' solver result message clearer
  crates/spk-solve/crates/graph/src/error.rs
  crates/spk-solve/crates/graph/src/graph.rs
  crates/spk-solve/crates/validation/src/error.rs
  crates/spk-solve/src/solver_test.rs
Labels: SPI AOI, SPI-0.41

#1095 Update whoami to address vulerability
  Cargo.lock
  Cargo.toml
  crates/spfs/src/config.rs
  crates/spfs/src/runtime/storage.rs
  crates/spfs/src/tracking/tag.rs
Labels: maintenance

#1039 Adds basic iteractive menu for inspecting current state of solver when stepping
  crates/spk-solve/src/io.rs
Labels: enhancement, SPI AOI, SPI-0.41

#1067 Add `--output-to-dir <path>` for solvers' output
  Cargo.lock
  crates/spk-cli/common/src/flags.rs
  crates/spk-solve/Cargo.toml
  crates/spk-solve/src/error.rs
  crates/spk-solve/src/io.rs
  crates/spk-solve/src/lib.rs
  cspell.json
Labels: enhancement, SPI AOI, SPI-0.41

#1097 Give the website check job a name
  .github/workflows/hugo-link-check.yml
Labels: maintenance

#1034 Distro compat range
  Cargo.lock
  crates/spk-config/src/config.rs
  crates/spk-schema/Cargo.toml
  crates/spk-schema/src/build_spec.rs
  crates/spk-schema/src/option.rs
  crates/spk-schema/src/v0/spec.rs
  docs/admin/config.md
Labels: SPI AOI

#1061 Fix `spk export` not respecting repository arguments
  Cargo.lock
  crates/spk-build/src/archive_test.rs
  crates/spk-cli/group3/Cargo.toml
  crates/spk-cli/group3/src/cmd_export.rs
  crates/spk-cli/group3/src/cmd_export_test.rs
  crates/spk-cli/group3/src/cmd_import_test.rs
  crates/spk-storage/Cargo.toml
  crates/spk-storage/src/lib.rs
  crates/spk-storage/src/storage/archive.rs
  crates/spk-storage/src/storage/mod.rs
  crates/spk-storage/src/storage/spfs.rs
Labels: bug, enhancement

#1099 Update mio to address vulnerability
  Cargo.lock
  Cargo.toml
  crates/spk-solve/Cargo.toml
Labels: maintenance

#1100 cargo update shlex to address vulnerability
  Cargo.lock
Labels: maintenance

#1101 Add host filtering options to spk search
  crates/spk-cli/group4/src/cmd_search.rs
Labels: enhancement, SPI AOI

#1102 Handle when multiple packages embed the same package
  crates/spk-schema/crates/foundation/src/version/compat.rs
  crates/spk-solve/src/solver.rs
  crates/spk-solve/src/solver_test.rs
Labels: bug, SPI AOI

#1107 Add repo name to 'opening repository' debug messages
  crates/spfs/src/config.rs
Labels: enhancement, SPI AOI

#1118 Preserve env vars generated by build_interactive_shell_command
  crates/spk-cli/cmd-env/src/cmd_env.rs
Labels: bug, SPI AOI

#1117 Add method to unlock tags manually
  crates/spfs/src/storage/fs/tag.rs
Labels: ILM in-use

#1119 Run check workflows on pull requests
  .github/workflows/cspell.yml
  .github/workflows/housekeeping.yml
  .github/workflows/hugo-link-check.yml
  .github/workflows/rust.yml
Labels: bug
