Repository spkenv/spk, pull requests merged in 2025-09, with the labels that each got.

#1254 Delete a.out file
  a.out
Labels: maintenance

#1260 Bugfix: spfs push stopped defaulting to origin for remote repo
  crates/spfs-cli/main/src/cmd_push.rs
Labels: bug

#1257 Lock tracing-subscriber to get text colors back
  Cargo.lock
  Cargo.toml
  crates/spk-cli/common/Cargo.toml
  crates/spk-storage/Cargo.toml
Labels: maintenance

#1265 Bugfix: annotation blob value syncing
  crates/spfs/src/sync.rs
  crates/spfs/src/sync_test.rs
Labels: bug

#1259 Restore coverage workflow but using grcov
  .github/workflows/coverage.yml
  .gitignore
  Makefile
  crates/spk-cli/common/src/flags.rs
  cspell.json
Labels: enhancement, SPI AOI

#1266 Fuse missing payload handling
  codecov.yml
  crates/spfs-vfs/src/fuse.rs
  crates/spfs/src/error.rs
Labels: enhancement
