Repository spkenv/spk, pull requests merged in 2025-05, with the labels that each got.

#1203 Dependency Upgrades
  Cargo.lock
  Cargo.toml
  crates/spfs-cli/main/Cargo.toml
  crates/spfs-cli/main/src/cmd_server.rs
  crates/spfs-encoding/Cargo.toml
  crates/spfs-encoding/src/binary_test.rs
  crates/spfs-proto/Cargo.toml
  crates/spfs-vfs/build.rs
  crates/spfs-vfs/src/fuse.rs
  crates/spfs/Cargo.toml
  crates/spfs/build.rs
  crates/spfs/src/bootstrap_test.rs
  crates/spfs/src/fixtures.rs
  crates/spfs/src/graph/platform_test.rs
  crates/spfs/src/server/payload.rs
  crates/spfs/src/storage/fs/renderer_unix.rs
  crates/spfs/src/storage/rpc/payload.rs
  crates/spfs/src/storage/rpc/repository.rs
  crates/spfs/src/tracking/tag_test.rs
  crates/spk-config/Cargo.toml
  crates/spk-schema/crates/tera/Cargo.toml
  crates/spk-storage/Cargo.toml
  cspell.json
Labels: maintenance, dependencies

#1212 Fix `spfs clean` failing if a tag namespace exists
  crates/spfs-cli/cmd-clean/src/cmd_clean.rs
  crates/spfs/src/clean.rs
  crates/spfs/src/clean_test.rs
  crates/spfs/src/config.rs
  crates/spfs/src/fixtures.rs
  crates/spfs/src/proto/conversions.rs
  crates/spfs/src/server/tag.rs
  crates/spfs/src/storage/fs/tag.rs
  crates/spfs/src/storage/tag.rs
  crates/spfs/src/storage/tag_namespace.rs
  crates/spfs/src/storage/tag_test.rs
Labels: bug

#1217 Add Resolvo examples to the Solver Usage documentation
  cspell.json
  docs-packages/README.md
  docs-packages/gcc-4.spk.yaml
  docs-packages/gcc-6.spk.yaml
  docs-packages/maya2019.spk.yaml
  docs-packages/maya2020.spk.yaml
  docs-packages/my-plugin.spk.yaml
  docs-packages/my-tool.spk.yaml
  docs-packages/qt.spk.yaml
  docs/use/solver.md
  website/layouts/shortcodes/tab.html
  website/layouts/shortcodes/tabs.html
Labels: documentation
